apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy.yaml
  - new-api.yaml
  - portal.yaml
  - portal-rbac.yaml
  - sandbox-manager.yaml
  - sandbox-manager-rbac.yaml
  - sandbox-template.yaml
  - warm-pool.yaml
