apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-portal
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: talos-portal
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: sandbox-manager
          imagePullPolicy: Always
